version: '3'
services:
  postgres: 
    image: postgres:latest 
    container_name: quote_pg
    env_file: 
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
volumes:
  postgres:
  