services:
  postgres: 
    image: postgres:latest 
    restart: always
    env_file: 
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
    networks: 
      - net
    healthcheck:
      test: pg_isready
      interval: 30s
      timeout: 20s
      retries: 10
networks:
  net:
    driver: bridge
volumes:
  pg:
  