services:
  # backend-migrate:
  #   build: ./
  #   entrypoint: /app db:migrate
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/quotes?sslmode=disable

  backend:
    container_name: quote_backend
    env_file: 
      - .env 
    ports:  
      - 8000:8000
    build: 
      context: .
      network: host
    networks: 
      - quotes_net
    healthcheck:
      interval: 1m
      timeout: 3s
      retries: 3
      test: wget --no-verbose --tries=1 --spider http://localhost::8000/ || exit 1
      start_period: 5s
      start_interval: 1s
  frontend:
    container_name: quote_frontend
    env_file: 
      - .env 
    ports:
      - 5173:5173
    tty: true
    volumes:
      - ./:/srv/app
    build: ./frontend
    depends_on:
      - backend
networks:
  quotes_net:
    external: true
volumes:
  pg:
  