version: '3'
services:
  postgres: 
    image: postgres:latest 
    container_name: quote_db
    env_file: 
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
    networks: 
      - net
    healthcheck:
      test: pg_isready
      interval: 30s
      timeout: 20s
      retries: 10
  # backend-migrate:
  #   build: ./
  #   entrypoint: /app db:migrate
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/quotes?sslmode=disable

  backend:
    container_name: quote_backend
    env_file: 
      - .env 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/quotes?sslmode=disable
    ports:  
      - 8000
    build: .
    depends_on: 
      postgres:
        condition: service_healthy
      # backend-migrate:
      #   condition: service_completed_successfully
    networks: 
      - net
  frontend:
    container_name: quote_frontend
    env_file: 
      - .env 
    ports:
      - 5173:5173
    tty: true
    volumes:
      - ./:/srv/app
    build: ./frontend
networks:
  net:
    driver: bridge
volumes:
  pg:
  