version: '3'
services:
  postgres: 
    image: postgres:latest 
    container_name: quote_db
    env_file: 
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
volumes:
  pg:
  